Updates to files
BHoM/SAP_Toolkit pull request #116
Opened 2023-08-18 11:11 UTC by EKAdebo

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #112 

Excel results methods updated, and parametric components split into files.

### Test files

### Changelog

### Additional comments

2023-08-18 11:12 UTC, EKAdebo commented
@BHoMBot  check compliance

2023-08-18 11:40 UTC, FraserGreenroyd requested changes
Please resolve the compliance issues reported

2023-08-18 14:22 UTC, EKAdebo commented
@BHoMBot check compliance

2023-08-18 14:25 UTC, EKAdebo commented
@BHoMBot check compliance

2023-08-18 14:28 UTC, EKAdebo commented
@BHoMBot check compliance

2023-08-18 14:31 UTC, EKAdebo commented
@BHoMBot check core
@BHoMBot check serialisation

2023-08-18 14:54 UTC, FraserGreenroyd requested changes

2023-08-18 14:54 UTC, FraserGreenroyd commented on SAP_Engine/Compute/ExcelResults.cs
> +            if (filenames == null || filenames.Count == 0) { return null; }
```suggestion
            if (filenames == null || filenames.Count == 0 || reportObjs == null || reportObjs.Count == 0 || reportObjs.Count != fileNames.Count)
                return null;
```

2023-08-18 14:54 UTC, FraserGreenroyd commented on SAP_Engine/Compute/ExcelResults.cs
> +
```suggestion
```

2023-08-18 14:57 UTC, EKAdebo commented
@BHoMBot check compliance

2023-08-18 15:00 UTC, EKAdebo commented
@BHoMBot check compliance

2023-08-18 16:17 UTC, FraserGreenroyd commented
@BHoMBot check core
@BHoMBot check serialisation

2023-08-21 08:35 UTC, FraserGreenroyd approved these changes
All fine now for the time being.

2023-08-21 08:35 UTC, merged