SAP_Toolkit: Replace Dwelling reference with Zone and Clean Bluebeam Markup
BHoM/SAP_Toolkit pull request #27
Opened 2021-11-16 11:09 UTC by emilsvedjer

### Issues addressed by this PR

Closes #26 
Closes #25 

### Additional comments
Replaced reference for dwelling to Zone since this reference was outdated
https://github.com/BHoM/BHoM/pull/1317

Created component to clean XML export from Bluebeam

2021-11-16 20:24 UTC, rboulton-BH approved these changes
LGTM

2021-11-24 11:32 UTC, FraserGreenroyd requested changes

2021-11-24 11:32 UTC, FraserGreenroyd commented on SAP_Engine/Modify/CleanBluebeamMarkup.cs
> +
```suggestion
```

2021-11-24 11:32 UTC, FraserGreenroyd commented on SAP_Engine/Modify/CleanBluebeamMarkup.cs
> +            if (!File.Exists(inputDirectory))
```suggestion
                return null;
                
            if (!File.Exists(inputDirectory))
```

2021-11-24 11:32 UTC, FraserGreenroyd commented on SAP_Engine/Modify/CleanBluebeamMarkup.cs
> +        public static string CleanBluebeamMarkup(string inputDirectory, bool run = false)
Let's have this take in a `FileSettings` object similar to an Adapter so that people can use it with both the XML Toolkit and this method

2021-11-24 11:32 UTC, FraserGreenroyd commented on SAP_Engine/Modify/CleanBluebeamMarkup.cs
> +            string outputDirectory = id.Replace(".xml", "_cleaned.xml");
Might be best to have the user specify the output file as Adapter FileSettings for flexibility

2021-11-29 09:29 UTC, FraserGreenroyd requested changes

2021-11-29 09:29 UTC, FraserGreenroyd commented on SAP_Engine/Modify/CleanBluebeamMarkup.cs
> +        [Input("run", "Toggle to acitvate the component.")]
```suggestion
        [Input("run", "Toggle to activate the component.")]
```

2021-11-29 09:29 UTC, FraserGreenroyd commented on SAP_Engine/Modify/CleanBluebeamMarkup.cs
> +        [Output("outputDirectory","Directory to the new file.")]
```suggestion
        [Output("outputDirectory", "Directory to the new file.")]
```

2021-11-29 09:29 UTC, FraserGreenroyd commented on SAP_Engine/Modify/CleanBluebeamMarkup.cs
> +                || !Path.HasExtension(fileSettingsOutput.FileName) || (Path.GetExtension(fileSettingsOutput.FileName) != ".xml" && Path.GetExtension(fileSettingsOutput.FileName) != ".csproj"))
We don't need the `csproj` check here

2021-11-29 09:29 UTC, FraserGreenroyd commented on SAP_Engine/Modify/CleanBluebeamMarkup.cs
> +            string outputDirectory = fileSettingsOutput.Directory + "\\" + fileSettingsOutput.FileName;
```suggestion
            }
            
            string outputDirectory = fileSettingsOutput.Directory + "\\" + fileSettingsOutput.FileName;
```

2021-11-29 09:29 UTC, FraserGreenroyd commented on SAP_Engine/SAP_Engine.csproj
> +      <HintPath>..\..\..\..\..\ProgramData\BHoM\Assemblies\Adapter_oM.dll</HintPath>
Get BHoMBot to run a compliance check on the project file and provide you with fixes for this.

2021-11-30 11:40 UTC, FraserGreenroyd commented
@BHoMBot fix project file ref. 4365889809

2021-11-30 11:40 UTC, FraserGreenroyd commented
@BHoMBot check project-compliance

2021-12-01 09:28 UTC, FraserGreenroyd requested changes

2021-12-01 09:28 UTC, FraserGreenroyd commented on SAP_Engine/Modify/CleanBluebeamMarkup.cs
> +
```suggestion
```

2021-12-01 09:29 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2021-12-01 12:06 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance

2021-12-01 12:07 UTC, FraserGreenroyd commented
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 4379307888

2021-12-01 12:07 UTC, FraserGreenroyd commented
@BHoMBot fix copyright headers ref. 4381015534

2021-12-01 12:07 UTC, FraserGreenroyd commented
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 4379307443

2021-12-01 12:08 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance

2021-12-01 12:08 UTC, FraserGreenroyd approved these changes

2021-12-01 12:08 UTC, merged