SAP_Toolkit: Defining objects in the SAP Toolkit
BHoM/SAP_Toolkit pull request #64
Opened 2022-11-03 14:32 UTC by EKAdebo

Defining objects in the SAP Toolkit from the Stroma SAP 10.2 JSON.

2022-11-03 14:52 UTC, FraserGreenroyd requested changes
I've checked the first 7 and have the following comments which I think will go through most of them, so stopping here for now to allow some fixes :smile:

 - `ID` should be with a capital D on all files
 - Acronyms/abbreviations should be avoided
 - `object` types should be put to a fixed type - we might need to have a think about what type they should be
 - Descriptions should be filled in - but I'm guessing that'll come later?

For the renaming - if you right click a variable you should get this dropdown:
![image](https://user-images.githubusercontent.com/18049174/199754264-15e838ad-2145-4599-a93f-aeeb1b9a4827.png)

Select this rename highlighted (second one down in my screenshot) and it'll rename the variable in all the places it's referenced in the code which should make some things easier for you :smile:

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/AAEGeneration.cs
> +        public virtual int Id { get; set; } = 0;
`ID` should have a capital `D` - if you right-click -> rename -> it should then rename throughout the codebase where you've used it.

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/AAEGeneration.cs
> +        public virtual int Id { get; set; } = 0;
Might also be worth setting the default to be `-1` so it's very obvious it's not been set?

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/AAEGeneration.cs
> +    public class AAEGeneration : BHoMObject
What is `AAE`? We should avoid acronyms in the object names please

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/AAEGeneration.cs
> +        public virtual double EGenerated { get; set; } = 0;
What is the `E` for here?

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/AAEGeneration.cs
> +        public virtual bool Include { get; set; } = false;
Include what?

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/Address.cs
> +        public virtual int Id { get; set; } = 0;
`ID`

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/Address.cs
> +        public virtual string Uprn { get; set; } = null;
What's this? Unique Postal Reference Number?

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/Address.cs
> +        public virtual string Country { get; set; } = null;
Can we make this an enum to match up with other objects using a `Country` variable? Maybe not for this PR - check with one of @kayleighhoude PRs, she's been using a `Country` enum somewhere we might be able to leverage with some refactoring.

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/Assessor.cs
> +        public virtual int Id { get; set; } = 0;
`ID`

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/Assessor.cs
> +        public virtual object LastName { get; set; } = null;
Is this matching the schema from Stroma? If so it's probably fine then as we need to work with their data model, but if not, I recommend we look to see if we can do this better [to be more inclusive](https://softwareengineering.stackexchange.com/questions/354885/modeling-first-and-lastname-separately)

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/Assessor.cs
> +        public virtual string Fax { get; set; } = null;
The 1980's called...

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/Boiler.cs
> +        public virtual int Id { get; set; } = 0;
`ID`

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/Boiler.cs
> +        public virtual bool FlowTempKnown { get; set; } = false ;
We should avoid acronyms and abbreviations in our variable names - can these have `Temperature` in full (if `Temp` is short for temperature and not temporary).

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/Boiler.cs
> +        public virtual bool PumpHp { get; set; } = false;
`Hp`?

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/ClientDetails.cs
> +        public virtual int Id { get; set; } = 0;
`ID`

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/ClientDetails.cs
> +        public virtual object CompanyName { get; set; } = null;
```suggestion
        public virtual string PhoneNumber { get; set; } = null;

        [Description("")]
        public virtual string FaxNumber { get; set; } = null;

        [Description("")]
        public virtual string Email { get; set; } = null;

        [Description("")]
        public virtual string CompanyName { get; set; } = null;
```

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/CommunityHeating.cs
> +        public virtual int Id { get; set; } = 0;
`ID`

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/CommunityHeating.cs
> +        public virtual List<object> HeatSources { get; set; } = null;
Do we not have a definition for a heat source so we don't have to do `List<object>`?

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/CommunityHeating.cs
> +        public virtual List<object> HeatSources { get; set; } = null;
Would also recommend making it default to a new list rather than `null`

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/CommunityHeating.cs
> +        public bool Boiler2Chp { get; set; } = false;
`Chp`?

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/CommunityHeating.cs
> +        public int NoOfAdditionalHeatSources { get; set; } = 0;
`Number` rather than `No`

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/CommunityWater.cs
> +        public virtual int NoOfAdditionalHeatSources { get; set; } = 0;
`Number`

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/CommunityWater.cs
> +        public virtual object SystemRef { get; set; } = null;
`Reference`

2022-11-03 14:52 UTC, FraserGreenroyd commented on SAP_oM/SAP10StromaJson/CommunityWater.cs
> +        public virtual object CommunityHeatingName { get; set; } = null;
```suggestion
        public virtual string CommunityHeatingName { get; set; } = null;
```

2022-11-24 16:25 UTC, rboulton-BH commented
PR resolves issue #65

2022-12-01 17:54 UTC, rboulton-BH approved these changes
Core functionality works as expected from testing with test scripts saved here: https://burohappold.sharepoint.com/:f:/s/BHoM/EibIMfqpyrNNjv8O2SgFACsBEFL7sd5lMvNfIWtbLlnERA?e=46hWXs

2022-12-01 18:21 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-12-02 10:56 UTC, EKAdebo commented
@BHoMBot check compliance

2022-12-02 11:00 UTC, EKAdebo commented
@BHoMBot fix copyright headers ref. 9844767340

2022-12-02 11:01 UTC, EKAdebo commented
@BHoMBot check copyright-compliance

2022-12-02 11:03 UTC, EKAdebo commented
@BHoMBot fix copyright headers ref. 9844839106

2022-12-02 11:16 UTC, EKAdebo commented
@BHoMBot check copyright-compliance

2022-12-02 11:17 UTC, EKAdebo commented
@BHoMBot check project-compliance

2022-12-02 11:30 UTC, jamesramsden-bh commented
@BHoMBot check compliance

2022-12-02 11:35 UTC, EKAdebo commented
@BHoMBot check core

2022-12-02 12:26 UTC, EKAdebo commented
@BHoMBot fix documentation punctuation ref. 9845380912

2022-12-02 14:00 UTC, FraserGreenroyd commented
@BHoMBot check project-compliance
@BHoMBot check copyright-compliance

2022-12-02 14:02 UTC, FraserGreenroyd approved these changes
Some compliance issues which we'll pick up in smaller PRs later as we go through the workflow.

2022-12-02 14:02 UTC, merged