SAP_Toolkit: Modification of model building objects
BHoM/SAP_Toolkit pull request #8
Opened 2021-03-01 14:03 UTC by linaeriksson

Closes #6

2021-03-02 20:58 UTC, FraserGreenroyd commented
@BHoMBot check project compliance

2021-03-02 20:59 UTC, FraserGreenroyd commented
@BHoMBot fix project file ref. 2016820539

2021-03-02 20:59 UTC, FraserGreenroyd commented
@BHoMBot check project compliance

2021-03-09 09:35 UTC, FraserGreenroyd commented
Discussion with @linaeriksson just now highlighted that the bug fix to Environment_Engine [here](https://github.com/BHoM/BHoM_Engine/pull/2376) should also fix the issue which is currently resolved with the comment `massive hack, do not deploy`. I'll get this investigated this morning ahead of this afternoon's call and report back to @linaeriksson accordingly.

2021-04-03 19:31 UTC, FraserGreenroyd requested changes
Some minor formatting. The majority of the code is ok though with some tidy up needed after we go through the next phase of prototyping and begin to work with what is in the `Environment_oM` core model objects (`Space`, `Zone`, etc.) and what is specific to the SAP process.

I would advise we delete all of the XML files just to keep this tidy - we don't need them now and discussions with @rboulton-BH shows we're going to move towards the more open source XML schema for SAP processes which renders these XML files not relevant anymore. They can be deleted entirely.

Will do another review after @rboulton-BH and @LivAndersson complete theirs following any potential bug fixes that may be required.

Otherwise, this is great work @linaeriksson :smile:

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_Engine/Compute/AssignSpaceType.cs
> +
Delete this blank line

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_Engine/Compute/AssignSpaceType.cs
> +        public static List<Space> AssignSpaceType(this List<Space> spaces, List<Point> searchPoints, string type, bool ignoreCase = true)
I think per discussion with @rboulton-BH this method will migrate up to the core engine. Happy for it to be merged as is for now though to aid prototyping, but commenting to remember for later/others to voice opinions.

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_Engine/Compute/ExtrudeToVolume.cs
> +
Delete this blank line

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_Engine/Compute/ExtrudeToVolume.cs
> +        public static List<Panel> ExtrudeToVolume(this BH.oM.Environment.SAP.Space space)
This will likely be replaced once we migrate the SAP process to better use existing Environment oM objects like `Environment.Space`. Happy to merge this for now following @rboulton-BH review, but long term plan should be to remove this once the proof of concept is done.

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_Engine/Create/DwellingInfo.cs
> +
Delete this blank line

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_Engine/Create/ExportFromSAPObjects.cs
> +            if (dwellingInfo.OrientationDegrees <= 315 && dwellingInfo.OrientationDegrees > 225)
I would reverse the order of the if's to give a banding that is easier to read on code reading. Current order is slightly confusing on first glance.

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_Engine/Create/TFA.cs
> +
Delete this blank line

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_Engine/Create/TFA.cs
> +
Delete 2 of these 3 blank lines

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_Engine/Create/ThermalBridges.cs
> +
Delete blank line

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_Engine/Create/ThermalBridges.cs
> +
Delete blank line

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_Engine/Create/Window.cs
> +            if (orientation >= 225 && orientation < 315)
Same here on reordering the statements

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_Engine/Modify/AddOpenings.cs
> +
Delete blank line

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_Engine/Query/IsOnLevel.cs
> +        public static bool IsOnLevel(this Polyline polyline, Level level, double tolerance = BH.oM.Geometry.Tolerance.Distance)
This should move to the core engine later

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_oM/Dwelling.cs
> +
Delete blank line

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_oM/MachineLearning/MachineLearningyada.cs
> +
Delete

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_oM/Space.cs
> +    public class Space : BHoMObject, IRegion
Long term we want to work with the `Environment.Space` object per discussion with @rboulton-BH

2021-04-03 19:31 UTC, FraserGreenroyd commented on SAP_oM/ThermalBridgesCurves.cs
> +        [Description("Staggered something - God knows - Ross knows")]
Does @rboulton-BH know 😉

2021-07-07 13:53 UTC, linaeriksson commented on SAP_oM/ThermalBridgesCurves.cs
> +        [Description("Staggered something - God knows - Ross knows")]
@rboulton-BH do you?

2021-07-07 13:55 UTC, linaeriksson commented
@BHoMBot check compliance

2021-07-07 13:58 UTC, linaeriksson commented
@BHoMBot check compliance

2021-07-07 13:59 UTC, linaeriksson commented
@BHoMBot check compliance

2021-07-07 14:00 UTC, linaeriksson commented
@BHoMBot check compliance

2021-07-22 15:40 UTC, FraserGreenroyd requested changes

2021-07-22 15:40 UTC, FraserGreenroyd commented on SAP_Engine/Create/SAPExport.cs
> +
```suggestion
```

2021-07-22 15:40 UTC, FraserGreenroyd commented on SAP_Engine/Create/SAPExport.cs
> +
```suggestion
```

2021-07-22 15:40 UTC, FraserGreenroyd commented on SAP_Engine/Create/ThermalBridges.cs
> +
```suggestion
```

2021-07-22 15:40 UTC, FraserGreenroyd commented on SAP_Engine/Create/ThermalBridges.cs
> +
```suggestion
```

2021-07-22 15:40 UTC, FraserGreenroyd commented on SAP_Engine/Create/ThermalBridges.cs
> +                ThermalBridges thermalBridge= new ThermalBridges();
```suggestion
                ThermalBridges thermalBridge = new ThermalBridges();
```

2021-07-22 15:40 UTC, FraserGreenroyd commented on SAP_Engine/Create/ThermalBridges.cs
> +            }
```suggestion
                thermalBridges.Add(thermalBridge);
            }
```

2021-07-22 15:40 UTC, FraserGreenroyd commented on SAP_Engine/Create/ThermalBridgesCurves.cs
> +
```suggestion
```

2021-07-22 15:40 UTC, FraserGreenroyd commented on SAP_Engine/Objects/BalconyLines.cs
> +﻿using System;
Needs copyright header

2021-07-22 15:40 UTC, FraserGreenroyd commented on SAP_Engine/Objects/PartyFloors.cs
> +﻿using System;
Needs copyright header

2021-07-22 15:40 UTC, FraserGreenroyd commented on SAP_Engine/Objects/ToOrientationText.cs
> +﻿using System;
Needs copyright header

2021-07-22 15:40 UTC, FraserGreenroyd commented on SAP_oM/ThermalBridgesCurves.cs
> +        [Description("Staggered something - God knows - Ross knows")]
Much like God, @rboulton-BH is silent to our prayers for answers...

2021-07-22 15:45 UTC, linaeriksson commented
@BHoMBot check copyright-compliance

2021-07-22 15:55 UTC, linaeriksson commented
@BHoMBot fix copyright headers ref. 3135768749

2021-07-23 10:20 UTC, linaeriksson commented
@BHoMBot check compliance

2021-07-23 13:52 UTC, linaeriksson commented
@BHoMBot check compliance

2021-07-23 13:56 UTC, FraserGreenroyd commented
@BHoMBot fix copyright headers ref. 3144138051

2021-07-23 13:58 UTC, FraserGreenroyd requested changes

2021-07-23 13:58 UTC, FraserGreenroyd commented on SAP_Engine/Modify/SnapInvertedCorners.cs
> +        public static Output<List<Space>, List<Panel>> SnapInvertedCorners(List<Space> spaces, List<Space> resnappedSpaces, List<Polyline> baseCurves, List<Panel> panels, double angleTolerance = BH.o
```suggestion
        public static Output<List<Space>, List<Panel>> SnapInvertedCorners(this List<Space> spaces, List<Space> resnappedSpaces, List<Polyline> baseCurves, List<Panel> panels, double angleTolerance = BH.oM.Geometry.Tolerance.Angle)
```

2021-07-23 13:58 UTC, FraserGreenroyd commented
@BHoMBot check compliance
@BHoMBot check core

2021-07-23 14:00 UTC, FraserGreenroyd commented
@BHoMBot check compliance
@BHoMBot check core

2021-07-23 14:03 UTC, FraserGreenroyd commented
@BHoMBot check compliance
@BHoMBot check core

2021-07-23 14:35 UTC, FraserGreenroyd approved these changes
Tested during handover with @linaeriksson - this is great work, tack så mycket @linaeriksson :smile:

2021-07-23 14:36 UTC, FraserGreenroyd commented
@BHoMBot check compliance
@BHoMBot check core

2021-07-23 15:31 UTC, FraserGreenroyd approved these changes
Approving following rebase

2021-07-23 15:31 UTC, merged