Including methods for parametrics on SAPReport object
BHoM/SAP_Toolkit pull request #87
Opened 2023-05-31 15:16 UTC by EKAdebo

### Issues addressed by this PR

Closes #85 

There have been methods included to parametrically change the SAP report object based on the u value, gvalues and orientations ( and some more)

2023-05-31 15:16 UTC, EKAdebo commented
@BHoMBot check compliance

2023-05-31 15:26 UTC, EKAdebo commented
@BHoMBot check compliance

2023-05-31 15:28 UTC, EKAdebo commented
@BHoMBot check compliance

2023-06-01 11:51 UTC, FraserGreenroyd requested changes
Done a quick review of the first few files @EKAdebo - it's looking good, just some minor code comments so far. Have to go to something else now so I figure I'll leave you with these for now, if you can double check all the other files for similar remarks just in case and then I'll try and come back to this when I next get some time. Sorry for the split nature of the review!

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/CheckInclude.cs
> +            List<string> test = toInclude.Select(x => x.Distinct().ToList()).ToList().SelectMany(x=> x).ToList();
```suggestion
            List<string> test = toInclude.Select(x => x.Distinct()).SelectMany(x => x).ToList();
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/CheckInclude.cs
> +            if (test.Count() != test.Distinct().Count())
```suggestion
            if (test.Count != test.Distinct().Count())
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/CheckInclude.cs
> +
```suggestion
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Floor.cs
> +                        floorObj = floorObj.ModifyFloor(uvalue,floorName);
```suggestion
                        floorObj = floorObj.ModifyFloor(uvalue, floorName);
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Floor.cs
> +                floor.Description= description;
```suggestion
                floor.Description = description;
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Floor.cs
> +            if (description != null)
If you want to save all the lines of an if statement, you could use this:

`floor.Description = (description != null ? description : tempDesc);`

The use of `?` is a ternary-operator and can make some statements like this a bit easier - obviously not well suited to multiple if-elseif-else type statements though.

You don't have to use it - just figured now was the right time to introduce another concept if you weren't already familiar with it 😄

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Mirror.cs
> +                    if (!(array == null))
```suggestion
                    if (array != null)
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Mirror.cs
> +            try
```suggestion
            }
            
            try
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Mirror.cs
> +                BH.Engine.Base.Compute.RecordWarning("If you have no PV ignore this warning, otherwise:" + e.Message);
```suggestion
                BH.Engine.Base.Compute.RecordWarning("If you have no PV ignore this warning, otherwise: " + e.Message);
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Mirror.cs
> +                        if (!(array == null))
```suggestion
                        if (array != null)
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Mirror.cs
> +                    List<BH.oM.Environment.SAP.XML.PhotovoltaicArray> FGHRSPVArrays = heating.FGHRSEnergySource.PhotovoltaicArrays.PhotovoltaicArray;
Lowercase variable names please

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Mirror.cs
> +                BH.Engine.Base.Compute.RecordWarning("If you have no PV ignore this warning, otherwise:" + e.Message);
```suggestion
                BH.Engine.Base.Compute.RecordWarning("If you have no PV ignore this warning, otherwise: " + e.Message);
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Mirror.cs
> +
```suggestion
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Mirror.cs
> +
```suggestion
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Mirror.cs
> +
```suggestion
        }
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Opening.cs
> +                        openingObj = openingObj.ModifyOpening(height,width,pitch);
```suggestion
                        openingObj = openingObj.ModifyOpening(height, width, pitch);
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/OpeningType.cs
> +                if (uvalue != 0.00)
Probably worth using a tolerance on this?

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/OpeningType.cs
> +            if (valid != false)
```suggestion
            if (valid)
```

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/OpeningType.cs
> +                    if (uvalue != 0.00)
Might want tolerances on this?

2023-06-01 11:51 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +        public static Output<List<SAPReport>, List<FileSettings>> ParametricStudy(this SAPReport sapObj, List<Parameters> iteration, FileSettings saveFile)
I will come back to this file on second review

2023-06-01 14:53 UTC, EKAdebo commented on SAP_Engine/Modify/Floor.cs
> +            if (description != null)
Nice! Thanks :)

2023-06-01 15:28 UTC, EKAdebo commented
@BHoMBot check compliance

2023-06-04 00:30 UTC, FraserGreenroyd requested changes

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Mirror.cs
> +
```suggestion

                propertyDetailsObj.Heating.MainHeatingDetails.MainHeating = heatingObjs;
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Mirror.cs
> +            int compassdirection = (orientationValue + 2 * (distance)) % 8;
```suggestion
            int compassDirection = (orientationValue + 2 * (distance)) % 8;
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Mirror.cs
> +                compassdirection = compassdirection + 8;
```suggestion
            if (compassDirection <= 0)
            {
                compassDirection += 8;
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Mirror.cs
> +            return compassdirection.ToString();
```suggestion
            return compassDirection.ToString();
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Opening.cs
> +            if (width != null)
```suggestion
            if (pitch != null)
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Opening.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/OpeningType.cs
> +        [Input("type", "New type name for the windows. For each type")]
Documentation appears unfinished

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/OpeningType.cs
> +                string name = string.Empty;
```suggestion
                string name = "";
```

A personal preference of mine, so happy for you to ignore this one.

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/OpeningType.cs
> +                    name = name = $"gvalue_{gvalue}_{name}";
```suggestion
                    name = $"gvalue_{gvalue}_{name}";
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/OpeningType.cs
> +                BH.Engine.Base.Compute.RecordError("Already a window type with these names."); //come back to this
```suggestion
                BH.Engine.Base.Compute.RecordError("Already a window type with these names."); //TODO: come back to this
```

Using `TODO` in code comments can help intellisense identify areas of 'to-do' items easily 😄

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/OpeningType.cs
> +                BH.Engine.Base.Compute.RecordError("Already a window type with these names."); //come back to this
Just ask @tg359 😝

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/OpeningType.cs
> +                    openingList.Add (openingObj);
```suggestion
                    openingList.Add(openingObj);
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +        [MultiOutput(0, "sapObjects", "Mulitple iterations of the sapObject.")]
```suggestion
        [MultiOutput(0, "sapObjects", "Multiple iterations of the sapObject.")]
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +        public static Output<List<SAPReport>, List<FileSettings>> ParametricStudy(this SAPReport sapObj, List<Parameters> iteration, FileSettings saveFile)
Ok, here we go on second review then...

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +                    BH.Engine.Base.Compute.RecordError("Please give all your iterations a name.");
Sassy! I like it

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +        [Description("")]
👀

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +        [Description("")]
👀

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +        [Description("")]
👀

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +        [Description("")]
👀

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricStudy.cs
> +        [Description("")]
👀

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricsUvalueGvalue.cs
> +            if (gSteps > 0 && (double.IsNaN(upperGValue) || double.IsNaN(lowerGValue)))
```suggestion
            }
            
            if (gSteps > 0 && (double.IsNaN(upperGValue) || double.IsNaN(lowerGValue)))
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricsUvalueGvalue.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricsUvalueGvalue.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricsUvalueGvalue.cs
> +            foreach ((var u, var g) in test)
👀 

Let's chat about this when we next catch up 😄

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Rotate.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Rotate.cs
> +            {
```suggestion
            int compassDirection = (Int32.Parse(orientation) + Int32.Parse(rotation)) % 8;

            if (compassDirection <= 0)
            {
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Rotate.cs
> +            return compassdirection.ToString();
```suggestion
                compassDirection += 8;
            }
            return compassDirection.ToString();
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Rotate.cs
> +            if (rotation == null || rotation == "0" || rotation == "9") return null;
```suggestion
            if (orientation == null || orientation == "0" || orientation == "9")
                return null;
                
            if (rotation == null || rotation == "0" || rotation == "9")
                return null;
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/Enums/Mirror.cs
> +		None = 0,
Can we sort the indentation on this please

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/Iteration/FloorIterator.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/Iteration/OpeningIterator.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/Iteration/OpeningTypeIterator.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/Iteration/OrientationIterator.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/Iteration/Parameters.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/Iteration/Parameters.cs
> +    [Description(".")]
👀

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/Iteration/Parameters.cs
> +        [Description("TB to change psi values - iterator")]
`TB`? Guessing Thermal Bridges? If so can we use the full name please

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/Iteration/RoofIterator.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/Iteration/RoofIterator.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/Iteration/ThermalBridgeIterator.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/Iteration/ThermalBridgeIterator.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/Iteration/WallIterator.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/Iteration/WallIterator.cs
> +
```suggestion
```

2023-06-04 00:30 UTC, FraserGreenroyd commented on SAP_oM/PsiValues.cs
> +
Delete all the extra lines please 😝

2023-06-05 11:20 UTC, EKAdebo commented on SAP_oM/Enums/Mirror.cs
> +		None = 0,
It doesn't look like that on my laptop...

2023-06-05 14:39 UTC, FraserGreenroyd commented on SAP_oM/Enums/Mirror.cs
> +		None = 0,
Huh... ok... odd! 🤷 Nevermind then!

2023-06-05 15:35 UTC, EKAdebo commented
@BHoMBot check compliance

2023-06-06 15:04 UTC, EKAdebo commented
@BHoMBot check compliance

2023-06-07 13:56 UTC, FraserGreenroyd requested changes

2023-06-07 13:56 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricsUvalueGvalue.cs
> +            if (uSteps > 0 && (upperUValue > 0 || lowerUValue > 0))
```suggestion
            if (uSteps > 0 && (upperUValue < 0 || lowerUValue < 0))
```

2023-06-07 13:56 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricsUvalueGvalue.cs
> +            if (gSteps > 0 && (upperGValue > 0 || lowerGValue > 0))
```suggestion
            if (gSteps > 0 && (upperGValue < 0 || lowerGValue < 0))
```

2023-06-07 13:56 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricsUvalueGvalue.cs
> +            List<(double, double)> test = uValues.SelectMany(u => gValues, (u, g) => (u, g)).ToList();
Rename the variable from `test` to something else such as `temp`

2023-06-07 13:56 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ParametricsUvalueGvalue.cs
> +            foreach ((var u, var g) in test)
Have caught up with this with @EKAdebo today, @EKAdebo has explained what it's doing and I'm happy this is the best approach for the problem presented so happy to make no further comment on this at this time.

2023-06-07 13:56 UTC, FraserGreenroyd commented on SAP_Engine/Modify/OpeningType.cs
> +            var valid = dict.Select(x => (include.Contains(x.Value))).Any(x => x == true);
```suggestion
            var valid = dict.Select(x => (include.Contains(x.Value))).Any(x => x);
```

2023-06-07 13:56 UTC, FraserGreenroyd commented on SAP_Engine/Modify/OpeningType.cs
> +            var valid = dict.Select(x => (include.Contains(x.Value))).Any(x => x == true);
Rename variable to `invalid`

2023-06-09 16:25 UTC, EKAdebo commented
@BHoMBot check compliance

2023-06-09 16:29 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-06-09 16:38 UTC, EKAdebo commented
@BHoMBot check compliance

2023-06-09 16:39 UTC, EKAdebo commented
@BHoMBot check compliance

2023-06-09 16:44 UTC, EKAdebo commented
@BHoMBot check core
@BHoMBot check serialisation

2023-06-13 15:44 UTC, FraserGreenroyd requested changes

2023-06-13 15:44 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Floor.cs
> +using System;
```suggestion

using System;
```

2023-06-13 15:44 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Opening.cs
> +using System;
```suggestion

using System;
```

2023-06-13 15:44 UTC, FraserGreenroyd commented on SAP_Engine/Modify/OpeningType.cs
> +using System;
```suggestion

using System;
```

2023-06-13 15:44 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Roof.cs
> +using System;
```suggestion

using System;
```

2023-06-13 15:44 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ThermalBridge.cs
> +using System;
```suggestion

using System;
```

2023-06-13 15:44 UTC, FraserGreenroyd commented on SAP_Engine/Modify/ThermalBridgesFromOpening.cs
> +
```suggestion
```

2023-06-13 15:44 UTC, FraserGreenroyd commented on SAP_Engine/Modify/Wall.cs
> +using System;
```suggestion

using System;
```

2023-06-13 15:44 UTC, FraserGreenroyd commented on SAP_oM/Iteration/FloorIterator.cs
> +
```suggestion
```

2023-06-13 15:44 UTC, FraserGreenroyd commented on SAP_oM/Iteration/OpeningIterator.cs
> +
```suggestion
```

2023-06-13 15:44 UTC, FraserGreenroyd commented on SAP_oM/Iteration/OpeningTypeIterator.cs
> +
```suggestion
```

2023-06-13 15:44 UTC, FraserGreenroyd commented on SAP_oM/Iteration/OrientationIterator.cs
> +
```suggestion
```

2023-06-13 15:44 UTC, FraserGreenroyd commented on SAP_oM/Iteration/Parameters.cs
> +
```suggestion
```

2023-06-13 15:46 UTC, FraserGreenroyd approved these changes
All looks good now, great work @EKAdebo

2023-06-13 15:47 UTC, FraserGreenroyd commented
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check serialisation

2023-06-13 15:51 UTC, merged